apiVersion: v1
kind: Service
metadata:
  name: cloud-backend-service
spec:
  type: NodePort
  selector:
    app: cloud-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080